In [24]:
import shutil
from pathlib import Path
import json

import polars as pl

In [26]:
results = pl.read_ndjson("results.jsonl").unnest("response")
results.head()

shape: (5, 7)
┌───────────────┬──────────────┬──────────────┬──────────────┬──────────────┬───────┬──────────────┐
│ source_file   ┆ criterion    ┆ study_result ┆ explanation  ┆ study_contra ┆ error ┆ raw_response │
│ ---           ┆ ---          ┆ ---          ┆ ---          ┆ dicts_rubric ┆ ---   ┆ ---          │
│ str           ┆ str          ┆ str          ┆ str          ┆ ---          ┆ str   ┆ str          │
│               ┆              ┆              ┆              ┆ bool         ┆       ┆              │
╞═══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪═══════╪══════════════╡
│ 1956b7b9-0b75 ┆ Includes     ┆ We           ┆ The study    ┆ false        ┆       ┆              │
│ -43a4-8ef6-e4 ┆ information  ┆ identified   ┆ result       ┆              ┆       ┆              │
│ f726…         ┆ that some…   ┆ 1,096        ┆ describes an ┆              ┆       ┆              │
│               ┆              ┆ patients a…  ┆ …            ┆              ┆       ┆              │
│ e5725a9f-859f ┆ Clarifies    ┆ ------------ ┆ The rubric   ┆ false        ┆       ┆              │
│ -4ec7-82f2-91 ┆ that iris    ┆ ------------ ┆ specifically ┆              ┆       ┆              │
│ c0cc…         ┆ prolapse i…  ┆ ------…      ┆ clarif…      ┆              ┆       ┆              │
│ 61b90306-ccb5 ┆ Describes    ┆ This cohort  ┆ The rubric   ┆ false        ┆       ┆              │
│ -42b7-89d2-b5 ┆ that         ┆ study invest ┆ criterion    ┆              ┆       ┆              │
│ 8dcf…         ┆ although     ┆ igated…      ┆ discusses…   ┆              ┆       ┆              │
│               ┆ some p…      ┆              ┆              ┆              ┆       ┆              │
│ 76092487-d17f ┆ Mentions     ┆ We           ┆ The rubric   ┆ false        ┆       ┆              │
│ -4bfd-825f-33 ┆ that living  ┆ identified   ┆ criterion    ┆              ┆       ┆              │
│ 3362…         ┆ kidney do…   ┆ patients who ┆ describes…   ┆              ┆       ┆              │
│               ┆              ┆ had…         ┆              ┆              ┆       ┆              │
│ fd59b9c2-4750 ┆ Correctly    ┆ This cohort  ┆ The rubric   ┆ false        ┆       ┆              │
│ -453a-a3de-a9 ┆ states that  ┆ study        ┆ focuses on   ┆              ┆       ┆              │
│ 9522…         ┆ the mana…    ┆ examined     ┆ tailorin…    ┆              ┆       ┆              │
│               ┆              ┆ tim…         ┆              ┆              ┆       ┆              │
└───────────────┴──────────────┴──────────────┴──────────────┴──────────────┴───────┴──────────────┘

In [27]:
errors = results.filter(pl.col("error") != "")
len(errors)

0

In [28]:
results.filter(pl.col("study_contradicts_rubric"))

shape: (18, 7)
┌───────────────┬──────────────┬──────────────┬──────────────┬──────────────┬───────┬──────────────┐
│ source_file   ┆ criterion    ┆ study_result ┆ explanation  ┆ study_contra ┆ error ┆ raw_response │
│ ---           ┆ ---          ┆ ---          ┆ ---          ┆ dicts_rubric ┆ ---   ┆ ---          │
│ str           ┆ str          ┆ str          ┆ str          ┆ ---          ┆ str   ┆ str          │
│               ┆              ┆              ┆              ┆ bool         ┆       ┆              │
╞═══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪═══════╪══════════════╡
│ b10b5474-861a ┆ Provides     ┆ see report   ┆ The rubric   ┆ true         ┆       ┆              │
│ -461e-93ef-16 ┆ links to the ┆              ┆ criterion    ┆              ┆       ┆              │
│ 7ab7…         ┆ source o…    ┆ This case    ┆ mandates …   ┆              ┆       ┆              │
│               ┆              ┆ includes…    ┆              ┆              ┆       ┆              │
│ 47c18c3f-4ced ┆ Describes    ┆ We           ┆ The rubric   ┆ true         ┆       ┆              │
│ -4e61-b070-67 ┆ the methods  ┆ identified   ┆ criterion    ┆              ┆       ┆              │
│ c614…         ┆ of inves…    ┆ patients who ┆ requires …   ┆              ┆       ┆              │
│               ┆              ┆ had…         ┆              ┆              ┆       ┆              │
│ e2ab624a-a05d ┆ Fills out    ┆ We analyzed  ┆ The rubric   ┆ true         ┆       ┆              │
│ -4101-9c88-ec ┆ fabricated   ┆ patients at  ┆ criterion    ┆              ┆       ┆              │
│ eef7…         ┆ sedation …   ┆ Stanfo…      ┆ requires …   ┆              ┆       ┆              │
│ b2f4a7e9-7399 ┆ Gives        ┆ We           ┆ The rubric   ┆ true         ┆       ┆              │
│ -43d1-8b73-b3 ┆ definitive   ┆ identified   ┆ expects a    ┆              ┆       ┆              │
│ 822a…         ┆ advice for   ┆ 2528         ┆ straightf…   ┆              ┆       ┆              │
│               ┆ or…          ┆ patients 75… ┆              ┆              ┆       ┆              │
│ 70c10085-1386 ┆ Instructs    ┆ We analyzed  ┆ The rubric   ┆ true         ┆       ┆              │
│ -441f-81f5-4d ┆ the user to  ┆ all children ┆ criterion    ┆              ┆       ┆              │
│ 21cf…         ┆ give the…    ┆ (aged…       ┆ directs t…   ┆              ┆       ┆              │
│ …             ┆ …            ┆ …            ┆ …            ┆ …            ┆ …     ┆ …            │
│ d8cbf5b5-ae23 ┆ FERGIcor     ┆ This cohort  ┆ The          ┆ true         ┆       ┆              │
│ -4a65-821f-a8 ┆ trials date  ┆ study        ┆ criterion    ┆              ┆       ┆              │
│ 47a8…         ┆ back to 2…   ┆ examined     ┆ specifies    ┆              ┆       ┆              │
│               ┆              ┆ tim…         ┆ that s…      ┆              ┆       ┆              │
│ 3d6c6016-d082 ┆ Suggests     ┆ We           ┆ The rubric   ┆ true         ┆       ┆              │
│ -46e0-abad-d8 ┆ that the     ┆ identified   ┆ criterion    ┆              ┆       ┆              │
│ 9be4…         ┆ Ottawa       ┆ adult        ┆ focuses e…   ┆              ┆       ┆              │
│               ┆ ankle…       ┆ patients a…  ┆              ┆              ┆       ┆              │
│ 1cbd2c6c-09fd ┆ Presents     ┆ In a case    ┆ The rubric   ┆ true         ┆       ┆              │
│ -46cc-bd66-c3 ┆ only         ┆ series from  ┆ instructs to ┆              ┆       ┆              │
│ b96e…         ┆ positive     ┆ 2017 to …    ┆ presen…      ┆              ┆       ┆              │
│               ┆ outcome…     ┆              ┆              ┆              ┆       ┆              │
│ 4663ac1d-7810 ┆ Suggests     ┆ In this case ┆ The rubric   ┆ true         ┆       ┆              │
│ -4922-94a0-e8 ┆ brand names  ┆ series of    ┆ requires     ┆              ┆       ┆              │
│ c0e4…         ┆ of variou…   ┆ patient…     ┆ suggestion…  ┆              ┆       ┆              │
│ 17293365-cade ┆ Provides     ┆ Using the    ┆ The rubric   ┆ true         ┆       ┆              │
│ -4d58-a61b-80 ┆ uncertainty  ┆ Stanford     ┆ criterion    ┆              ┆       ┆              │
│ 5e50…         ┆ of eviden…   ┆ database, w… ┆ requires …   ┆              ┆       ┆              │
└───────────────┴──────────────┴──────────────┴──────────────┴──────────────┴───────┴──────────────┘

In [ ]:
input_dir = Path(
    "/Users/max/Developer/repos/HealthBench/src/simple_evals/improvement/examples_of_bad_static_criteria/opensearch/to_ingest"
)
contradictions_dir = Path("contradictions")
for row in results.filter(pl.col("study_contradicts_rubric")).iter_rows(named=True):
    input_file = input_dir / row["source_file"]
    output_file = contradictions_dir / row["source_file"]
    out_data = json.loads(input_file.read_text())
    out_data["explanation"] = row["explanation"]
    output_file.write_text(json.dumps(out_data, indent=2))